name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions: read-all

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # See https://nodejs.org/en/about/releases/
                node-version: [20.x]

        env:
            SOUFFLE_DEB: https://github.com/souffle-lang/souffle/releases/download/2.4.1/x86_64-ubuntu-2004-souffle-2.4.1-Linux.deb
            SOL_AST_COMPILER_CACHE: ${{ github.workspace }}/.compiler_cache
            SOLC_TYPED_AST_REPO: ${{ github.workspace }}/../solc-typed-ast
            SOLC_TYPED_AST_DIR: ${{ github.workspace }}/../solc-typed-ast/src

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  repository: ConsenSys/solc-typed-ast
                  path: $SOLC_TYPED_AST_REPO

            - name: Use NodeJS ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            # See https://souffle-lang.github.io/source
            # See https://github.com/souffle-lang/souffle/releases
            - name: Install Soufflé
              run: |
                  sudo apt update && sudo apt install -y libffi7 mcpp build-essential
                  wget $SOUFFLE_DEB -O /tmp/souffle.deb
                  sudo dpkg -i /tmp/souffle.deb
                  souffle --version

            - name: Install and lint
              run: |
                  echo $SOLC_TYPED_AST_REPO
                  echo $SOLC_TYPED_AST_DIR
                  npm install
                  npm link
                  npm run lint
                  sol-datalog-cli --version

            # See https://github.com/ethereum/solc-bin
            # See https://binaries.soliditylang.org/
            - name: Pre-download compilers from historical builds archive
              run: sol-datalog-cli --download-compilers native wasm

            - name: Test and generate coverage report
              run: npm test
